# Generated by Django 5.0.6 on 2024-07-09 02:01

import Singer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Singer', '0003_tag_singer_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Singer.models.image_upload_path),
        ),
    ]
